version: 2
jobs:
  build:
    docker:
      - image: 'circleci/node:latest'
    steps:
      - checkout
      - restore_cache:
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
            # fallback to using the latest cache if no exact match is found
            - yarn-packages-
      - run:
          name: install
          command: yarn install
      - save_cache:
          paths: 
            - node_modules
          key: yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: release
          command: yarn semantic-release || true
